language: node_js
node_js:
  - "node"
  - "lts/*"

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - yarn test:coverage
  - yarn e2e

after_success:
  - bash <(curl -s https://codecov.io/bash)
